server:
  port: 9089
  servlet:
    context-path: /api/v1
    session:
      timeout: 18000
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: 100MB
    max-http-post-size: 100MB
    connection-timeout: 60000
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/html,text/plain
    min-response-size: 1024
spring:
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    locale-resolver: fixed
    locale: zh_CN
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  main:
    allow-circular-references: true
  devtools:
    restart:
      enabled: false
  thymeleaf:
    cache: false
  cache:
    redis:
      time-to-live: 86400000
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    - classpath*:mybatis/mapper/*.xml
upload:
  dir: ./uploads